name: minerva_analysis
channels:
  - conda-forge
dependencies:
  - appdirs
  - dask
  - elementpath
  - flask=2.1
  - flask-sqlalchemy=2.5.1
  - hdbscan
  - itsdangerous
  - jinja2
  - joblib
  - llvmlite
  - matplotlib
  - numba
  - numpy
  - numpy-indexed
  - ome-types
  - orjson
  - pandas
  - pillow
  - pip
  - python=3.10
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sqlalchemy=1.4.41
  - tifffile=2023.7.10
  - umap-learn
  - waitress
  - werkzeug
  - xmlschema
  - zarr
  - pydantic=1.10.8

  # For pycave (to be installed via pip)
  - pytorch::cpuonly
  - pytorch::pytorch>=1.12,<2.0
  - pytorch-lightning>=1.9,<2.0
  - torchmetrics>=0.11,<0.12

  - pip:
    - opencv-python
    # Install the following with pip install --no-dependencies
    # - lightkit
    # - pycave
